#pragma once
#include "Utils/Array.h"
#include <stdio.h>


enum class hyEventType
{
	NONE, 

	/* these are mostly only needed for the editor: */
	KEY_PRESS, KEY_RELEASE,  
	MOUSE_MOVE, MOUSE_CLICK, MOUSE_SCROLL,

	WINDOW_RESIZE, WINDOW_FOCUS, WINDOW_UNFOCUS, WINDOW_CLOSE,

	/* these may be more useful with an openXR runtime: */
	SURFACE_FOCUS, SURFACE_UNFOCUS,

	LEFT_STICK_MOVE,	 LEFT_STICK_PRESS,      RIGHT_STICK_MOVE,     RIGHT_STICK_PRESS,
	LEFT_TRIGGER_PRESS,  LEFT_TRIGGER_RELEASE,  RIGHT_TRIGGER_PRESS,  RIGHT_TRIGGER_RELEASE,
	LEFT_BUTTON_1_PRESS, LEFT_BUTTON_1_RELEASE, RIGHT_BUTTON_1_PRESS, RIGHT_BUTTON_1_RELEASE,
	LEFT_BUTTON_2_PRESS, LEFT_BUTTON_2_RELEASE, RIGHT_BUTTON_2_PRESS, RIGHT_BUTTON_2_RELEASE,


};

enum class hyEventCategory
{
	NONE, 
	IO_EVENT,
	RENDER_EVENT
};
